<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./src/statics/models/adult.glb
-->

<script>
  import { Group, MeshStandardMaterial, BufferGeometry } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import { adultModified } from "../stores";

  const gltf = useGltf(`src/statics/models/adult-v1.glb`, { useDraco: true });

  const component = forwardEventHandlers();

  export let ref;

  $: if ($gltf) {
    const geometry = $gltf.nodes.adult.geometry;
    ref = geometry;
    if (!$adultModified) {
      geometry.scale(0.1, 0.1, 0.1);
      geometry.translate(0, -0.5, 0);
      $adultModified = true;

      // const geoJSON = geometry.toJSON();
      // console.log(JSON.stringify(geoJSON));
    }
  }
</script>

{#await gltf}
  <slot name="fallback" />
{:then gltf}
  <!-- <T.Mesh
    geometry="{gltf.nodes.adult.geometry}"
    material="{gltf.nodes.adult.material}"
    scale="{0.1}"
  /> -->
  <T
    is={gltf.nodes.adult.geometry}
    dispose={false}
    {...$$restProps}
    bind:this={$component} />
  <!-- <T.BoxGeometry args="{[0.15, 1.0, 0.15]}" /> -->
  <!-- <T.MeshStandardMaterial color="red" /> -->
{:catch error}
  <slot name="error" {error} />
{/await}
