<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./src/statics/models/child.glb
-->

<script>
  import { T, forwardEventHandlers } from '@threlte/core';
  import { useGltf } from '@threlte/extras';
  import { childModified } from '../stores';

  const gltf = useGltf(`src/statics/models/child-v1.glb`, { useDraco: true });

  const component = forwardEventHandlers();

  $: if ($gltf) {
    const geometry = $gltf.nodes.child.geometry;

    if (!$childModified) {
      geometry.scale(0.1, 0.1, 0.1);
      geometry.translate(0, -0.25, 0);
      $childModified = true;
    }
  }
</script>

<!-- <T is="{ref}" dispose="{false}" {...$$restProps} bind:this="{$component}"> -->
{#await gltf}
  <slot name="fallback" />
{:then gltf}
  <!-- <T.Mesh
      geometry="{gltf.nodes.child.geometry}"
      material="{gltf.nodes.child.material}"
    /> -->
  <T
    is="{gltf.nodes.child.geometry}"
    dispose="{false}"
    {...$$restProps}
    bind:this="{$component}"
  />
{:catch error}
  <slot name="error" {error} />
{/await}

<slot {ref} />
<!-- </T> -->
